SERVER_IP = "http://192.168.0.182"

OLLAMA_API_URL = f"{SERVER_IP}:11434"
OLLAMA_API_GENERATE_COMPLETION_URL = f"{OLLAMA_API_URL}/api/generate"
OLLAMA_API_GENERATE_CHAT_COMPLETION_URL = f"{OLLAMA_API_URL}/api/chat"

AUTOMATIC1111_API_URL = f"{SERVER_IP}:9000"
AUTOMATIC1111_API_GENERATE_URL = f"{AUTOMATIC1111_API_URL}/sdapi/v1/txt2img"